#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        enabled: true
#      execution:
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 150000
#    createAccount:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 150000
#  threadpool:
#    priority-1-pool:
#      coreSize: 20
#      allowMaximumSizeToDivergeFromCoreSize: true
#      maximumSize: 70
#      queueSizeRejectionThreshold: 0
#      maxQueueSize: 0
#      keepAliveTimeMinutes: 2

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 50
  instances:
    createAccount:
      registerHealthIndicator: true
      failureRateThreshold: 50
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      eventConsumerBufferSize: 10
      ignore-exceptions: com.sharedservices.endpoint.BadRequestException

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 5s
      cancelRunningFuture: true
  instances:
    createAccount:
      eventConsumerBufferSize: 10
